Module3-task1
htmlacademy-adaptive/2004035-cat-energy-27 pull request #3
Opened 2022-12-14 11:30 UTC by ViktorSeniukov

2022-12-15 11:20 UTC, Dima-Dim requested changes
Почему файлы БЭМ-блоков разложены по папкам? Получается, например, блок `navigation` может быть использован только в header? Какое-то очень ограниченное переиспользование блоков получается.

В файлах самих блоков тоже нужно навести порядок.

2022-12-15 11:20 UTC, Dima-Dim commented on source/sass/Footer/address.scss
> +.addres__info--wrapper {
`addres` -> `address`

2022-12-15 11:20 UTC, Dima-Dim commented on source/sass/Main-Catalog/catalog-list.scss
> +.card-list {
Это какой-то другой блок.

2022-12-15 11:20 UTC, Dima-Dim commented on source/sass/Main-Catalog/more-products-card.scss
> +.more-products-card-table {
Тоже пошёл какой-то другой блок.

2022-12-15 11:20 UTC, Dima-Dim commented on source/sass/Main-Form/comments.scss
> +.form-wrapper__comments {
Тут вообще нет ни одного селектора для блока `comments`.

2022-12-17 10:20 UTC, ViktorSeniukov commented on .stylelintrc
> +    "at-rule-no-unknown": null
Это на скринкасте было
9:19
https://up.htmlacademy.ru/profession/frontender/15/adaptive/27/module/3/item/8

2022-12-18 05:21 UTC, Dima-Dim commented on .stylelintrc
> +    "at-rule-no-unknown": null
Ну раз сама Академия накосячила, тогда ладно, надеюсь они это учтут во время автоматических проверок на защите.

2022-12-19 07:16 UTC, ViktorSeniukov commented on source/form.html
> +          <fieldset class="form-wrapper form-wrapper__name">
А корректно будет сделать `__name --> --name --landlord` и тд?
Там изменяется только `padding`

2022-12-19 11:50 UTC, Dima-Dim commented on source/form.html
> +          <fieldset class="form-wrapper form-wrapper__name">
Да, можно сделать модификаторами.

2022-12-19 13:19 UTC, Dima-Dim requested changes
Не забывать про замечания линтера.

2022-12-19 13:19 UTC, Dima-Dim commented on source/sass/live-example-slider.scss
> +.slider-before {
Почему это здесь?

2022-12-19 13:19 UTC, Dima-Dim commented on source/sass/other.scss
> +.form-wrapper--other {
Это тоже не понятно почему в этом файле.

2022-12-19 13:19 UTC, Dima-Dim commented on source/sass/promo.scss
> +.promo-wrapper {
Это тоже теперь совсем другой блок, который должен быть в своём файле.

2022-12-19 13:19 UTC, Dima-Dim commented on source/sass/textarea.scss
> +.form-wrapper--comments {
Тоже какая-то не стыковка названия и содержания файла.

2022-12-19 13:19 UTC, Dima-Dim commented on source/catalog.html
>        <section class="address section section--darker">
`section--darker` модификатор без блока. Перепровериться yoksel.github.io/html-tree/

2022-12-19 14:33 UTC, ViktorSeniukov commented on source/sass/live-example-slider.scss
> +.slider-before {
Изменил названия, тк мне кажется что выносить это отдельно странно.
Потому что там будет пару селекторов

2022-12-22 03:59 UTC, Dima-Dim requested changes
[form-wrapper--landlord.scss](https://github.com/htmlacademy-adaptive/2004035-cat-energy-27/pull/3/files/f1983119a1b25cc05eeb62c1d3c9784de54466f7..6455ea47c0db82ec3d9e5ed04f73da0c45399462#diff-8ddca7993f3c032ed41267435b95f90441ccf4d98a5ee14ae9ba0c3207e8e6a5) это как это так? :) У нас файлы для блоков, а внутри стили только для этих блоков.
Тоже самое касается и других подобных файлов.

2022-12-22 03:59 UTC, Dima-Dim commented on source/form.html
> +              <input class="form-input form-input-with-icon form-input-with-icon--email" type="email" id="email" pattern="a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" placeholder="kuklachev@gmail.com" req
`form-input form-input-with-icon` название второго блока звучит как модификатор первого :) `form-input-with-icon` на самом деле смодостаточный блок который может существовать сам по себе?

2022-12-22 03:59 UTC, Dima-Dim commented on source/index.html
> +                <img class="live-example__slider-image live-example__slider-after__image" src="./img/live-example-after.png" alt="Как кот выглядит после." width="280" height="256">
Что такое `live-example__slider-after__image`?

2022-12-22 03:59 UTC, Dima-Dim commented on source/sass/live-example-slider.scss
> +.live-example__slider-before {
Читаешь название элемента и понимаешь что это какая-то фигня :) Не должно быть элементов для псевдоэлементов, это противоречит тому, для чего они были придуманы. И если тебе такое требуется, то нужно посмотреть на то, что получается и подумать как это можно сделать иначе, более логично и правильно.

2022-12-22 03:59 UTC, Dima-Dim commented on source/sass/live-example-slider.scss
> +.live-example__slider-after__image {
По этому потом появляются вот такие вот недоразумения которые уже вообще в БЭМ не вписываются.

2022-12-28 13:47 UTC, Dima-Dim requested changes

2022-12-28 13:47 UTC, Dima-Dim commented on source/form.html
> +            <p class="form-title title-with-line">Контактные данные<br>(владельца кота)</p>
Почему тут теперь одновременно два БЭМ блока?

2022-12-28 13:47 UTC, Dima-Dim commented on source/form.html
> +              <input class="form-input input-with-icon input-with-icon--email" type="email" id="email" pattern="a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" placeholder="kuklachev@gmail.com" required>
Тут тоже `input-with-icon` должно было стать `input--with-icon` по логике отражённой в названии класса.

2022-12-28 13:47 UTC, Dima-Dim commented on source/sass/control-mark.scss
> +.control-input[type="checkbox"]:checked + .control-mark--check {
Это другой блок.

2022-12-28 13:48 UTC, Dima-Dim commented
Осталось совсем чуть-чуть до того, чтобы логика БЭМ сошлась.

2022-12-29 12:31 UTC, ViktorSeniukov commented on source/form.html
> +            <p class="form-title title-with-line">Контактные данные<br>(владельца кота)</p>
Пока не хотел это добавлять, забыл убрать

2023-01-02 15:29 UTC, Dima-Dim requested changes

2023-01-02 15:29 UTC, Dima-Dim commented on source/form.html
> +              <input class="form-input input--with-icon input--with-icon_email" type="email" id="email" pattern="a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" placeholder="kuklachev@gmail.com" required>
`input--with-icon_email` -- это отделение модификатора, - это разделение слов, а _ что?

2023-01-02 15:29 UTC, Dima-Dim commented on source/sass/control-input.scss
> +.control-input[type="checkbox"]:checked + .control-mark--check {
Тут всё ещё селектор от другого блока `control-mark`.

2023-01-02 15:29 UTC, Dima-Dim commented on source/sass/input.scss
> +  &_email {
Написал в разметке что это не вписывается в текущую нотацию.

2023-01-05 11:04 UTC, ViktorSeniukov commented on source/form.html
> +              <input class="form-input input--with-icon input--with-icon_email" type="email" id="email" pattern="a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" placeholder="kuklachev@gmail.com" required>
Модификатор `with-icon` со значением `email`

2023-01-12 14:32 UTC, Dima-Dim requested changes

2023-01-12 14:32 UTC, Dima-Dim commented on source/sass/Components/button.scss
> +    font-family: "Oswald", sans-serif;
Не нужно описывать стили которые уже были описаны для этого селектора выше и не требуют изменения.

2023-01-12 14:32 UTC, Dima-Dim commented on source/sass/card-item.scss
> +.card-item-table {
Это стили другого блока, которые должны быть описаны в своём файле.

2023-01-12 14:32 UTC, Dima-Dim commented on source/sass/catalog-list.scss
> +.catalog__title {
В этом файле могут быть только стили блока `catalog-list`.

2023-01-12 14:32 UTC, Dima-Dim commented on source/sass/form.scss
> +.form-main__title {
Это уже другой блок. Если это так, то он должен быть описан в другом файле.

2023-01-12 14:32 UTC, Dima-Dim commented on source/sass/form.scss
> +.form-wrapper {
А это какой-то третий блок.

2023-01-12 14:32 UTC, Dima-Dim commented on source/sass/global.scss
> +.visually-hidden {
Всё это я бы тоже рекомендовал разнести по своим файлам. Ведь всё это отдельные блоки.

2023-01-12 14:32 UTC, Dima-Dim commented on source/sass/header.scss
> +.main-header {
Я думаю уже понятно что такой мешанины из блоков в файлах стилей быть не должно.

2023-01-13 10:52 UTC, ViktorSeniukov commented on source/sass/Components/button.scss
> +    font-family: "Oswald", sans-serif;
это потом

2023-01-13 14:24 UTC, merged